name: quick_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.0
  firebase_core: ^3.9.0
  intl: ^0.20.1
  linear_progress_bar: ^1.1.3
  provider: ^6.1.2
  firebase_auth: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
